#port => default 8080 => 보안 설정(AWS) : port 허용
# 8080 / 1521 / 3306 (MySql , MariaDB)
# MVC 설정
server:
    port: 8080
    servlet:
      context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
    username: root
    password: asd123
    driver-class-name: com.mysql.cj.jdbc.Driver

  #ai:
   # google:
    #  genai:
     #   api-key: 
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
    
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml

# MyBatis : 복잡한 SQL => Annotation / XML(JOIN, 동적쿼리)
# 프로시저 / 트리거 / 함수
# JPA => JOIN => CRUD
# WebSocket 설정 / Kafka 설정 / MSA 설정
# Security : 람다식